spring.application.name=tp8-monitoring
server.port=8081

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers,env,beans
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/monitoring
management.info.env.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.slo.http.server.requests=10ms,50ms,100ms,200ms,500ms,1s
spring.thymeleaf.check-template-location=false
info.application.name=Spring Monitoring Application
info.application.version=1.0.0
info.application.description=Enterprise Monitoring Solution
info.application.environment=development

logging.level.root=WARN
logging.level.ma.ens.tp8monitoring=DEBUG
logging.file.name=logs/tp8-monitoring.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

server.error.include-message=always
server.error.include-binding-errors=always